version: '3'

services:      
  db:
    build: .docker/postgres
    container_name: postgresdb
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db      